### ISSUE TITLE
NoMethodError (undefined method `text' for nil:NilClass) reading XLSX file

### ISSUE THREAD

**Issue by rui-castro** [roo-rb/roo#122]
The error happens in https://github.com/Empact/roo/blob/master/lib/roo/excelx.rb:542

Full stacktrace:
```ruby
["/home/tobias/.rvm/gems/ruby-1.9.3-p545/bundler/gems/roo-56e2e61d1ad9/lib/roo/excelx.rb:542:in `block in read_hyperlinks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/nokogiri-1.6.1/lib/nokogiri/xml/node_set.rb:237:in `block in each'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/nokogiri-1.6.1/lib/nokogiri/xml/node_set.rb:236:in `upto'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/nokogiri-1.6.1/lib/nokogiri/xml/node_set.rb:236:in `each'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/bundler/gems/roo-56e2e61d1ad9/lib/roo/excelx.rb:541:in `read_hyperlinks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/bundler/gems/roo-56e2e61d1ad9/lib/roo/excelx.rb:299:in `hyperlink'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/bundler/gems/roo-56e2e61d1ad9/lib/roo/excelx.rb:292:in `hyperlink?'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/bundler/gems/roo-56e2e61d1ad9/lib/roo/excelx.rb:376:in `set_cell_values'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/bundler/gems/roo-56e2e61d1ad9/lib/roo/excelx.rb:466:in `block (2 levels) in read_cells'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/nokogiri-1.6.1/lib/nokogiri/xml/node_set.rb:237:in `block in each'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/nokogiri-1.6.1/lib/nokogiri/xml/node_set.rb:236:in `upto'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/nokogiri-1.6.1/lib/nokogiri/xml/node_set.rb:236:in `each'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/bundler/gems/roo-56e2e61d1ad9/lib/roo/excelx.rb:415:in `block in read_cells'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/nokogiri-1.6.1/lib/nokogiri/xml/node_set.rb:237:in `block in each'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/nokogiri-1.6.1/lib/nokogiri/xml/node_set.rb:236:in `upto'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/nokogiri-1.6.1/lib/nokogiri/xml/node_set.rb:236:in `each'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/bundler/gems/roo-56e2e61d1ad9/lib/roo/excelx.rb:391:in `read_cells'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/bundler/gems/roo-56e2e61d1ad9/lib/roo/excelx.rb:137:in `cell'", "/home/tobias/work/DynamicValue/dynamicvalue.git/app/models/report_wrapper_roo.rb:12:in `cell_value'", "/home/tobias/work/DynamicValue/dynamicvalue.git/app/models/report.rb:230:in `update_report_cached_data'", "/home/tobias/work/DynamicValue/dynamicvalue.git/app/models/report.rb:197:in `process_report'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:420:in `_run__166215516__save__805330915__callbacks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/callbacks.rb:264:in `create_or_update'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/persistence.rb:84:in `save'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/validations.rb:50:in `save'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/attribute_methods/dirty.rb:22:in `save'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/transactions.rb:259:in `block (2 levels) in save'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/transactions.rb:208:in `transaction'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/transactions.rb:259:in `block in save'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/transactions.rb:258:in `save'", "/home/tobias/work/DynamicValue/dynamicvalue.git/app/controllers/admin/reports_controller.rb:53:in `block in create'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal/mime_responds.rb:270:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal/mime_responds.rb:270:in `retrieve_collector_from_mimes'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal/mime_responds.rb:194:in `respond_to'", "/home/tobias/work/DynamicValue/dynamicvalue.git/app/controllers/admin/reports_controller.rb:52:in `create'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal/implicit_render.rb:4:in `send_action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:167:in `process_action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal/rendering.rb:10:in `process_action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/abstract_controller/callbacks.rb:18:in `block in process_action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:436:in `_run__345037530__process_action__191762075__callbacks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/abstract_controller/callbacks.rb:17:in `process_action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal/rescue.rb:29:in `process_action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `block in instrument'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in `instrument'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `instrument'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:29:in `process_action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/railties/controller_runtime.rb:18:in `process_action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:121:in `process'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:45:in `process'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal.rb:203:in `dispatch'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_controller/metal.rb:246:in `block in action'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:73:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:36:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:608:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/head.rb:14:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/params_parser.rb:21:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/flash.rb:242:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/cookies.rb:341:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/query_cache.rb:64:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activerecord-3.2.17/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `_run__1023837737__call__805330915__callbacks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:27:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/reloader.rb:65:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/railties-3.2.17/lib/rails/rack/logger.rb:32:in `call_app'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in `block in call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/tagged_logging.rb:22:in `tagged'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/request_id.rb:22:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.17/lib/active_support/cache/strategy/local_cache.rb:72:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.17/lib/action_dispatch/middleware/static.rb:63:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/railties-3.2.17/lib/rails/engine.rb:484:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/railties-3.2.17/lib/rails/application.rb:231:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/railties-3.2.17/lib/rails/rack/log_tailer.rb:17:in `call'", "/home/tobias/.rvm/gems/ruby-1.9.3-p545/gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'", "/home/tobias/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'", "/home/tobias/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'", "/home/tobias/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'"]
```

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Does any one know if this issue still exists in the current version of Roo?

**Comment by stevendaniels** [comment]
It's been two weeks without a response, I recommend closing this issue.
