### ISSUE TITLE
Undefined namespace prefix

### ISSUE THREAD

**Issue by samstarling** [roo-rb/roo#138]
Has anyone ever come across an error like this when parsing an `.xlsx` file?

```
/task/__gems__/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/node.rb:159:in `evaluate': Undefined namespace prefix: /xmlns:sst/xmlns:si (Nokogiri::XML::XPath::SyntaxError)
    from /task/__gems__/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/node.rb:159:in `block in xpath'
    from /task/__gems__/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/node.rb:150:in `map'
    from /task/__gems__/gems/nokogiri-1.6.2.1/lib/nokogiri/xml/node.rb:150:in `xpath'
    from /task/__gems__/gems/roo-1.13.2/lib/roo/excelx.rb:610:in `read_shared_strings'
    from /task/__gems__/gems/roo-1.13.2/lib/roo/excelx.rb:94:in `block in initialize'
    from /task/__gems__/gems/roo-1.13.2/lib/roo/base.rb:565:in `block in make_tmpdir'
    from /usr/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
    from /task/__gems__/gems/roo-1.13.2/lib/roo/base.rb:564:in `make_tmpdir'
    from /task/__gems__/gems/roo-1.13.2/lib/roo/excelx.rb:80:in `initialize'
    from /task/__gems__/gems/roo-1.13.2/lib/roo/spreadsheet.rb:19:in `new'
    from /task/__gems__/gems/roo-1.13.2/lib/roo/spreadsheet.rb:19:in `open'
    from /task/basic_scraper.rb:14:in `parse_excel'
    from /task/justerini_brooks_scraper.rb:10:in `initialize'
    from /task/justerini_brooks_scraper.rb:127:in `new'
    from /task/justerini_brooks_scraper.rb:127:in `<top (required)>'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from __runner__.rb:213:in `<main>'
```

[Here's the file](https://dl.dropboxusercontent.com/u/107508/full.xlsx) I'm trying to parse. I'm using v1.13.2.

**Comment by quentindemetz** [comment]
#150 fixes this - can we please release ? Is there anything I can do to get this moving along ?
