### ISSUE TITLE
undefined method `upto' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by vtrkanna** [roo-rb/roo#164]
HI

We are facing one issue, we don't know what's problem. 

     /home/vtrkanna/.rvm/gems/ruby-2.1.2@rails4-dev/gems/roo-1.13.2/lib/roo/base.rb:266:in `row': undefined method `upto' for nil:NilClass (NoMethodError)

Our Code
      file = "/home/vtrkanna/Workspace/Rails4-devt/public/Article.xls"
    
      spreadsheetx = Roo::Spreadsheet.open(file, extension: :xls)
      -#spreadsheet = Roo::Spreadsheet.open(file)

     header = spreadsheetx.row(1)
    (2..spreadsheetx.last_row).each do |i|
         row = Hash[[header, spreadsheetx.row(i)].transpose]
         puts row["Name "]
     end
ISSUE
     /home/vtrkanna/.rvm/gems/ruby-2.1.2@rails4-dev/gems/roo-1.13.2/lib/roo/base.rb:266:in `row': undefined method `upto' for nil:NilClass (NoMethodError)

Help us

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Have you been able to replicate the issue with the current version of Roo?

**Comment by stevendaniels** [comment]
It's been two weeks without a response, I recommend closing this issue.

**Comment by stevendaniels** [comment]
@vtrkanna 
Can you create a gist for this issue?

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by vtrkanna** [comment]
Give me 1 week time, I will check and let you know

**Comment by ohaleck** [comment]
@stevendaniels 
I confirm the problem is still in version 2.0.0.
Please find the gist with an offending xlsx file and some irb code at: https://gist.github.com/ohaleck/1fd1761f168d28633e9d
Thanks for taking time to look into it!

**Comment by ohaleck** [comment]
@stevendaniels please let me know if there is anything (like a donation) that we could do to have the issue fixed. Thanks!

**Comment by stevendaniels** [comment]
@ohaleck Sorry about the delay. Thanks for the gist.

This error is caused by attempting to query an empty `Excelx::Sheet`. `Excelx::Sheet#first_row` (and last_row, first_column, last_column) returns the first non-empty row (or column). In this case, none of the cells on the first sheet have any values (even though the cells are formatted), so nil is returned.

There are definitely situations where accessing empty rows or columns would be useful. Unfortunately, loading empty rows and columns could significantly increase the memory usage of Roo for many users. Spreadsheets with only a few rows of data and then 10K + empty rows occur quite frequently.

Depending on your use case, there are some ways to get around this issue. 
Could you elaborate on what you are trying to do?

**Comment by stevendaniels** [comment]
I think the best way to address this issue is for Roo to raise a custom, more informative error. I'm open to suggestions.

**Comment by kuldeepaggarwal** [comment]
@stevendaniels I have also tried to parse an empty excel sheet and got same error, so I think we should handle this situation and return empty array if we called `to_a` on the spreadsheet.

```
workbook = ::Roo::Spreadsheet.open(file_path)
workbook.sheet(sheet_name).to_a # => raising same error., where `sheet_name` is the name of empty sheet name.
```

**Comment by kirykr** [comment]
@kuldeepaggarwal that could be so helpful if you have solved this problems
 :to loop through a row which has one or more empty cell values.

Thanks

**Comment by kuldeepaggarwal** [comment]
I didn't understand you, can you please elaborate this your solution?

**Comment by kirykr** [comment]
```
workbook = ::Roo::Spreadsheet.open(file_path)
workbook.sheet(sheet_name).to_a # => raising same error., where `sheet_name` is the name of empty sheet name.
```
i got an error like you did...

**Comment by stevendaniels** [comment]
Spent some more time looking into this. It's a pretty tricky issue.

Roo's sheets depend on methods like `first_row` and `last_row`. These methods 
usually return integers, but if the sheet is empty, will return `nil`. Unfortunately,
this `nil` value goes up the stack until it reaches of the methods that use `upto`
to iterate through rows and columns. 

Ideally, Roo should return an empty sheet, and an empty row or column. I'll work
on adding such behaviors in the next major version of Roo. The reason this will 
need a major version is it will break the behavior for users expecting those row/column
methods to return an integer or nil value.

**Comment by kirykr** [comment]
Very appreciate that @stevendaniels

**Comment by lehug** [comment]
not done yet?
which method can be used to check if the sheet is empty?  I need this method.
if empty, I will skip this sheet.

**Comment by marksiemers** [comment]
@lehug - This is a simplified version of a workaround that I ended up with:
```ruby
spreadsheet = Roo::Spreadsheet.open(file)
spreadsheet.default_sheet = 'Sheet1'
if spreadsheet.first_row.nil?
  do_some_error_handling
else
  process_normally
end
```

The call to `first_row` is the important part, I'm sure there are other ways to call it without having to use the default sheet.
