### ISSUE TITLE
Unintuitive error when wrong encoding used

### ISSUE THREAD

**Issue by agrimm** [roo-rb/roo#264]
If you use the wrong encoding when creating a StringIO object containing a spreadsheet, you get an unintuitive error message.

See https://github.com/agrimm/roo_encoding_replication for a full replication, but basically if you do

    # Oops, I forgot to use binread, giving the wrong encoding
    text = File.read(filename)
    string_io = StringIO.new(text, 'r')
    Roo::Spreadsheet.open(string_io, extension: :xlsx)

you get

        undefined method `name' for nil:NilClass
     # /Users/agrimm/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/roo-2.1.1/lib/roo/excelx.rb:423:in `each'
     # /Users/agrimm/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/roo-2.1.1/lib/roo/excelx.rb:423:in `sort_by'
     # /Users/agrimm/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/roo-2.1.1/lib/roo/excelx.rb:423:in `process_zipfile'

By contrast, the "spreadsheet" gem (and by implication roo-xls) forces the correct encoding.

Either fixing the encoding, or producing a more informative error message, would be satisfactory.

**Comment by stevendaniels** [comment]
In this example, is the StringIO object an xls spreadsheet?

**Comment by agrimm** [comment]
I'm pretty sure it's an `.xlsx` spreadsheet, not an `.xls` spreadsheet. If it were an `.xls` spreadsheet, it'd give a `Zip::Error` exception instead. Also, using `binread` wouldn't fix the problem if it were an `xls` spreadsheet.

In the repo I linked to, I included both the `.numbers` file and the `.xlsx` file. I exported the spreadsheet from `.numbers` into `.xlsx` format from Apple Numbers.

**Comment by stevendaniels** [comment]
Thanks for the details. I'm investigating this issue.
