### ISSUE TITLE
xlsx.formatted_value(1, 1) crashes if value is formatted as currency (€).

### ISSUE THREAD

**Issue by patricks** [roo-rb/roo#377]
I found a bug if I try to parse a € formatted cell.

Here is a example code snippet:

```ruby
xlsx = Roo::Spreadsheet.open("./tmp/euro_format_test.xlsx", extension: :xlsx)

price_raw = xlsx.cell(1, 1)
puts "DBG: price raw: #{price_raw}"

price_xlsx = xlsx.excelx_value(1, 1)
puts "DBG: price xlsx: #{price_xlsx}"

price_xlsx_type = xlsx.excelx_type(1, 1)
puts "DBG: price xlsx: #{price_xlsx_type}"

# here the demo fails
price = xlsx.formatted_value(1, 1)
puts "DBG: price: #{price}"
```

Here is the crash output:

```
TypeError: no implicit conversion of nil into String
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/roo-2.7.1/lib/roo/excelx/cell/number.rb:37:in `format'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/roo-2.7.1/lib/roo/excelx/cell/number.rb:37:in `formatted_value'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/roo-2.7.1/lib/roo/excelx.rb:445:in `safe_send'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/roo-2.7.1/lib/roo/excelx.rb:213:in `formatted_value'
	from /Users/patrick/Developer/mepp/mepp-testing/app/jobs/xlsx_content_import_job.rb:20:in `perform'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activejob-4.2.7.1/lib/active_job/execution.rb:32:in `block in perform_now'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activejob-4.2.7.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:342:in `block in simple'
... 27 levels...
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/patrick/Developer/mepp/mepp-backend/bin/rails:9:in `<top (required)>'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/patrick/.rvm/gems/ruby-2.3.1@mepp/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/patrick/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/patrick/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Here is the demo xlsx file:

[euro_format_test.xlsx](https://github.com/roo-rb/roo/files/701126/euro_format_test.xlsx)

Any ideas how to fix this problem?

**Comment by stevendaniels** [comment]
Thanks for raising this issue. Unfortunately, Roo can't currently handle custom formats properly. In this case, the best it could do is to return the string contents of your cell. 

Parsing custom formats is quite hard. Without a better understanding of the format spec, it would be very difficult to process correctly. I will do some research on the issue (`ECMA-376 18.8.31` seems to have the relevant information).

Based on your file, it looks like Roo isn't parsing the styles (i.e. format) correctly. 

```
  <numFmts count="1">
    <numFmt numFmtId="164" formatCode="&quot;€&quot;\ #,##0.00"/>
  </numFmts>
```

This should result in the following format `"€ #,##0.00"`, but we are getting `"\"€\"\\ #,##0.00"` instead.

**Comment by stevendaniels** [comment]
I will work on the fix, but in the meantime, adding this code should prevent the error

```
class Roo::Excelx::Cell::Number
        def formatted_value
          return @cell_value if Excelx::ERROR_VALUES.include?(@cell_value)

          formatter = formats[@format]
          if formatter.is_a? Proc
            formatter.call(@cell_value)
          elsif zero_padded_number?
            "%0#{@format.size}d" % @cell_value
          else
            Kernel.format(formatter, @cell_value)
          end
        rescue
          @cell_value
        end
end
```

**Comment by pattycg** [comment]
It seems to prevent the error, but it doesn't seem to solve the problem, which is that we should be able to get the formatted value with the currency symbol included.
