### ISSUE TITLE
2.7.0 breaking on reading CSV files from S3 or local folder

### ISSUE THREAD

**Issue by jotterlei** [roo-rb/roo#378]
After updating from 2.5.1 to 2.7.1 a CSV reading with Roo broke in our application.  I traced it to 2.6.0 working fine and then 2.7.0 breaking.

### Stack trace
```
Errno::ENOENT - No such file or directory @ rb_sysopen - https://BUCKET.s3.amazonaws.com/uploads/d/attachment/file/45/roster_01012017.csv:
  /Users/jotterlei/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1265:in `open'
  /Users/jotterlei/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1339:in `read'
  /Users/jotterlei/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1344:in `readlines'
  roo (2.7.0) lib/roo/csv.rb:101:in `set_row_count'
  roo (2.7.0) lib/roo/csv.rb:66:in `read_cells'
  roo (2.7.0) lib/roo/base.rb:145:in `row'
  app/services/import_roster.rb:41:in `read_file'
```

### Contents of roster_01012017.csv Stack trace
```
FirstName,MiddleName,LastName
Chuck,,Evans
Robby,,Jones
Jack,,Nicholas
Franz,,Ouimet
Daniel,,Duval
```

### Rails console showing error and stack trace
```
[5] pry(main)> Roo::Spreadsheet.open("https://cloudscoring.s3.amazonaws.com/uploads/d/attachment/file/45/roster_01012017.csv", extension: "csv").row(1)
Errno::ENOENT: No such file or directory @ rb_sysopen - https://BUCKET.s3.amazonaws.com/uploads/d/attachment/file/45/roster_01012017.csv
from /Users/jotterlei/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1265:in `initialize'
[6] pry(main)> wtf?
Exception: Errno::ENOENT: No such file or directory @ rb_sysopen - https://BUCKET.s3.amazonaws.com/uploads/d/attachment/file/45/roster_01012017.csv
--
0: /Users/jotterlei/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1265:in `initialize'
1: /Users/jotterlei/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1265:in `open'
2: /Users/jotterlei/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1265:in `open'
3: /Users/jotterlei/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1339:in `read'
4: /Users/jotterlei/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/csv.rb:1344:in `readlines'
5: /Users/jotterlei/.rvm/gems/ruby-2.3.1/gems/roo-2.7.0/lib/roo/csv.rb:101:in `set_row_count'
6: /Users/jotterlei/.rvm/gems/ruby-2.3.1/gems/roo-2.7.0/lib/roo/csv.rb:66:in `read_cells'
7: /Users/jotterlei/.rvm/gems/ruby-2.3.1/gems/roo-2.7.0/lib/roo/base.rb:145:in `row'
8: (pry):3:in `__pry__'
9: /Users/jotterlei/.rvm/gems/ruby-2.3.1/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
[7] pry(main)> 

```

**Comment by thbar** [comment]
Potentially related to #374.

**Comment by salmanasiddiqui** [comment]
Our unit test started to fail, a csv file is being read and imported. After the upgrade to v2.7, every row of CSV had only first column, rest of the data isn't being parsed I think.
CSV:
```
01/01/2012 0:00:00,100,120,120,121
01/01/2013 0:00:00,99.5,120,120,121
```
Input:
```
puts sheet.row(1)
puts sheet.row(2)
```
output (v2.6):
```
01/01/2012 0:00:00
100
120
120
121
01/01/2013 0:00:00
99.5
120
120
121
```
output (v2.7):
```
01/01/2012 0:00:00
01/01/2013 0:00:00
```

**Comment by matiasgarcia** [comment]
Has anyone found a workaround for this? Looks like downgrading roo to 2.6.0 works, but 2.7.0 is way more performant than 2.6.0
