### ISSUE TITLE
Missing required wookbook file

### ISSUE THREAD

**Issue by trungnd95** [roo-rb/roo#382]
I try to using roo gem to handle with excel file. I install following instruction but it not run correctly. 
Some error was shown. I try to fix this and install in many other machine, but still not run. 

**ArgumentError: missing required workbook file
	from /home/trung/.rvm/gems/ruby-2.0.0-p648/gems/roo-2.7.1/lib/roo/excelx/workbook.rb:25:in `initialize'
	from /home/trung/.rvm/gems/ruby-2.0.0-p648/gems/roo-2.7.1/lib/roo/excelx/shared.rb:24:in `new'
	from /home/trung/.rvm/gems/ruby-2.0.0-p648/gems/roo-2.7.1/lib/roo/excelx/shared.rb:24:in `workbook'
	from /home/trung/.rvm/gems/ruby-2.0.0-p648/gems/roo-2.7.1/lib/roo/excelx.rb:82:in `method_missing'
	from /home/trung/.rvm/gems/ruby-2.0.0-p648/gems/roo-2.7.1/lib/roo/excelx.rb:324:in `extract_worksheet_ids'
	from /home/trung/.rvm/gems/ruby-2.0.0-p648/gems/roo-2.7.1/lib/roo/excelx.rb:409:in `process_zipfile_entries'
	from /home/trung/.rvm/gems/ruby-2.0.0-p648/gems/roo-2.7.1/lib/roo/excelx.rb:390:in `process_zipfile'
	from /home/trung/.rvm/gems/ruby-2.0.0-p648/gems/roo-2.7.1/lib/roo/excelx.rb:57:in `initialize'
	from (irb):5:in `new'
	from (irb):5
	from /home/trung/.rvm/rubies/ruby-2.0.0-p648/bin/irb:12:in `<main>'**
Any one who faced with this error before. Please help me! Thanks alot!

**Comment by lizvdk** [comment]
I got that error when I:

1. downloaded an xlsx file
2. opened it with Apple's Numbers application
3. manually switched the extension to `.xlsx` 
4. attempted it to upload/parse it with roo

**Comment by quangle** [comment]
👍  same problem with me

**Comment by pdgonzalez872** [comment]
does it work with Ruby 2.2.x? Or is it the same behavior?

**Comment by SekharBeri** [comment]
Hi Guys, I too have the same problem any update on this. I am using Ruby 2.2.3

**Comment by ashwinbalaguru** [comment]
Facing the same problem, using version ruby 2.3.1

**Comment by Probablyility** [comment]
Just had the same problem with a small testing file I was running which I had opened locally in Excel to remove records with hopes of making my testing more straightforward. When I ran the much larger original file, which has never been opened in locally in Excel the file ran with no issues. 

Using the larger file will make my testing a little more complicated, but clearly the simple act of opening the file locally in Excel and saving it can change something that roo doesn't like.

**Comment by lsantobuono** [comment]
Sory to bring this up.
Still happens to me in 2.6.3, with xlsx generated by LibreOffice, and also with xlsx that are generated with the gem caxlsx_rails.
Problem happens wether i open the files manually or not after them being generated.
Any ideas on what the problem might be?

**Comment by louiced** [comment]
I don't know what the problem is, but I solved it by copying the content to a google spreadsheet and the downloading it with the correct extension (.xlsx). Hope that helps anyone!
