### ISSUE TITLE
Permissions denied issue

### ISSUE THREAD

**Issue by oprogfrogo** [roo-rb/roo#46]
I get the error below when trying to get an excel file: 

Errno::EACCES: Permission denied - oo_1404_4197352129

I think roo is trying to save the excel file to a temp directory. Anyone know where it's trying to write to?

**Comment by itsmechlark** [comment]
Hi. It happens to also. Hopefully this log might help:

```
2016-01-18T05:29:22.004Z 22399 TID-or0e0fvcc WARN: Errno::EACCES: Permission denied @ rb_sysopen - /var/www/cdasiaonline/releases/20160118042400/tmp/roo_Batch_3.xlsx20160118-22399-4ukg8d/roo_workbook.xml
2016-01-18T05:29:22.004Z 22399 TID-or0e0fvcc WARN: /var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/rubyzip-1.1.7/lib/zip/entry.rb:582:in `initialize'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/rubyzip-1.1.7/lib/zip/entry.rb:582:in `open'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/rubyzip-1.1.7/lib/zip/entry.rb:582:in `create_file'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/rubyzip-1.1.7/lib/zip/entry.rb:154:in `extract'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/bundler/gems/roo-d9667fc1f457/lib/roo/excelx.rb:307:in `extract_worksheet_ids'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/bundler/gems/roo-d9667fc1f457/lib/roo/excelx.rb:388:in `process_zipfile_entries'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/bundler/gems/roo-d9667fc1f457/lib/roo/excelx.rb:369:in `process_zipfile'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/bundler/gems/roo-d9667fc1f457/lib/roo/excelx.rb:45:in `initialize'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/bundler/gems/roo-d9667fc1f457/lib/roo/spreadsheet.rb:11:in `new'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/bundler/gems/roo-d9667fc1f457/lib/roo/spreadsheet.rb:11:in `open'
/var/www/cdasiaonline/releases/20160118042400/app/jobs/citation_finder_job.rb:164:in `perform'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activejob-4.2.5/lib/active_job/execution.rb:32:in `block in perform_now'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/active_job.rb:46:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/active_job.rb:46:in `perform'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/active_job.rb:20:in `block (3 levels) in <top (required)>'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `instance_exec'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `block in simple'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `block in around'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/marginalia-1.3.0/lib/marginalia/railtie.rb:37:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/marginalia-1.3.0/lib/marginalia/railtie.rb:37:in `block (2 levels) in insert_into_active_job'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `instance_exec'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `block in simple'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `block in around'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activejob-4.2.5/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `instance_exec'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `block in simple'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `block in around'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activejob-4.2.5/lib/active_job/logging.rb:23:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activejob-4.2.5/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activejob-4.2.5/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activejob-4.2.5/lib/active_job/logging.rb:45:in `tag_logger'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activejob-4.2.5/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `instance_exec'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `block in simple'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `block in around'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activejob-4.2.5/lib/active_job/execution.rb:31:in `perform_now'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activejob-4.2.5/lib/active_job/execution.rb:21:in `execute'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/activejob-4.2.5/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-failures-0.4.5/lib/sidekiq/failures/middleware.rb:9:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/var/www/cdasiaonline/shared/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

System Info:
1 cores
494 MB RAM
Debian 8.2
Linux 3.16.0-4-amd64 x86_64

**Comment by itsmechlark** [comment]
It's a 414K file. I already tested it with 883K file. 
What happen is that first 2 files succeeded and the next files failed with `Permission denied`. So, I checked the tmp dir, the direction mention didn't exist.

**Comment by itsmechlark** [comment]
In my local machine everything is working fine.

**Comment by Kagetsuki** [comment]
@itsmechlark As was pointed out above: was the file open in excel/calc wile you tried to read it? Was it closed cleanly?

**Comment by itsmechlark** [comment]
@Kagetsuki, I didn't open it excel/calc it's running in active_job(sidekiq). So, I don't think that the issue. Thanks.
