### ISSUE TITLE
Can't open some XLSX files [crash]

### ISSUE THREAD

**Issue by k06a** [roo-rb/roo#74]
```
Exception: index -1 too small for array; minimum: 0
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/excelx.rb:551:in `[]='
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/excelx.rb:551:in `block (2 levels) in process_zipfile'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/excelx.rb:525:in `each'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/excelx.rb:525:in `block in process_zipfile'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/zip-2.0.2/lib/zip/zip.rb:1387:in `open'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/excelx.rb:524:in `process_zipfile'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/excelx.rb:568:in `block in extract_content'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/zip-2.0.2/lib/zip/zip.rb:1387:in `open'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/excelx.rb:567:in `extract_content'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/excelx.rb:87:in `block in initialize'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/base.rb:565:in `block in make_tmpdir'
	C:/Ruby200_32/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/base.rb:564:in `make_tmpdir'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/excelx.rb:79:in `initialize'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/spreadsheet.rb:19:in `new'
	C:/Ruby200_32/lib/ruby/gems/2.0.0/gems/roo-1.12.2/lib/roo/spreadsheet.rb:19:in `open'
	C:/root/Projects/StatTree/StatTree2.rb:316:in `parse_xls'
	C:/root/Projects/StatTree/StatTree2.rb:447:in `parse_file'
	C:/root/Projects/StatTree/StatTree2.rb:501:in `block in <top (required)>'
	C:/root/Projects/StatTree/StatTree2.rb:497:in `each'
	C:/root/Projects/StatTree/StatTree2.rb:497:in `<top (required)>'
	-e:1:in `load'
	-e:1:in `<main>'
```

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Have you been able to replicate the issue with the current version of Roo?

**Comment by stevendaniels** [comment]
@simonoff No response after two weeks. I recommend closing this issue.

**Comment by k06a** [comment]
I can not find these files any more. Sorry.
