### ISSUE TITLE
String dates with a format of date cause a NoMethodError error

### ISSUE THREAD

**Issue by railsgirl42** [roo-rb/roo#97]
I have a xls spreadsheet where there is a column of dates, one of the dates is stored as a string '20012014. I have no control over the spreadsheets as they are uploaded by users. 

The following error is raised when trying to open the spreadsheet

```
undefined method `round' for #<String:0x7fdc4aefd7a0> (NoMethodError)
/app/shared/bundle/ruby/1.9.1/gems/spreadsheet-0.8.3/lib/spreadsheet/excel/row.rb:63:in `_datetime'
/app/shared/bundle/ruby/1.9.1/gems/spreadsheet-0.8.3/lib/spreadsheet/excel/row.rb:21:in `datetime'
/app/shared/bundle/ruby/1.9.1/gems/roo-1.11.1/lib/roo/excel.rb:310:in `read_cell_date_or_time'
/app/shared/bundle/ruby/1.9.1/gems/roo-1.11.1/lib/roo/excel.rb:256:in `block (2 levels) in read_cells'
/app/shared/bundle/ruby/1.9.1/gems/roo-1.11.1/lib/roo/excel.rb:250:in `each'
/app/shared/bundle/ruby/1.9.1/gems/roo-1.11.1/lib/roo/excel.rb:250:in `block in read_cells'
/app/shared/bundle/ruby/1.9.1/gems/spreadsheet-0.8.3/lib/spreadsheet/worksheet.rb:133:in `block in each'
/app/shared/bundle/ruby/1.9.1/gems/spreadsheet-0.8.3/lib/spreadsheet/worksheet.rb:132:in `upto'
/app/shared/bundle/ruby/1.9.1/gems/spreadsheet-0.8.3/lib/spreadsheet/worksheet.rb:132:in `each'
/app/shared/bundle/ruby/1.9.1/gems/spreadsheet-0.8.3/lib/spreadsheet/excel/worksheet.rb:35:in `each'
/app/shared/bundle/ruby/1.9.1/gems/roo-1.11.1/lib/roo/excel.rb:249:in `read_cells'
/app/shared/bundle/ruby/1.9.1/gems/roo-1.11.1/lib/roo/generic_spreadsheet.rb:99:in `last_row'
```

If I open the same spreadsheet using the Spreadsheet gem directly it does not have an error. I need to support xls and xlsx so using the Spreadsheet gem directly is not an option.

I am using Roo 1.11.1 and Ruby 1.9.3.

**Comment by stevendaniels** [comment]
This issue seems to affect an older version of Roo.
Does any one know if this issue still exists in the current version of Roo?

**Comment by stevendaniels** [comment]
No responses after 6 weeks. I'm closing this issue.
